export const PASSWORD_RULES = ['8 characters', '1 number', '1 special character', '1 uppercase', '1 lowercase'];

export const TERMS = [
  'Lorem augue lorem sit volutpat risus lectus nunc ornare amet. Urna velit nulla non molestie nullam euismod felis pharetra. Ac nullam urna et etiam laoreet dui. Turpis amet non laoreet vitae. Adipiscing dignissim amet nulla interdum cursus ultricies. Nascetur ac ut nec amet diam nisl sed quis. Viverra mattis justo viverra ipsum. Eget semper nec ligula etiam orci nam.\n' +
  'Odio pellentesque dui id ullamcorper vel in. Volutpat sodales id velit non facilisi. Bibendum consequat fermentum in non a eros odio amet varius. Arcu feugiat laoreet scelerisque etiam neque facilisis nisl. Condimentum est felis.',
  'Integer gravida imperdiet ullamcorper massa ac aliquam maecenas nisi. Ac in augue adipiscing sit tellus enim urna in. Posuere aenean venenatis mi faucibus justo massa arcu arcu. Luctus ultricies fermentum quis vulputate. Velit tortor quam ipsum nisl magna consectetur justo vitae. Felis at dignissim a fusce nunc sit. Egestas maecenas tellus nunc ipsum placerat purus nunc. Orci placerat vulputate massa lacinia velit pretium in. Quisque elementum facilisis morbi lectus aliquam. Cras hac cras amet at lobortis. Commodo turpis a egestas in feugiat feugiat montes eget blandit. Pretium dolor praesent enim eu aliquam eu.\n',
  'Imperdiet feugiat eget ac ornare felis elementum. Nisi malesuada egestas varius hendrerit. Et facilisi consectetur varius sed. Nibh scelerisque aliquet in nunc cras erat iaculis eu. Platea nunc montes morbi massa egestas. Pretium faucibus leo diam sagittis tempus. Fermentum lobortis eget orci platea dolor orci vel volutpat ut. Blandit sagittis magna cras lectus. Fames pulvinar elit dis duis fringilla tortor. Ultricies ut sit in malesuada elit cursus sed arcu platea. Enim ipsum sagittis a sit imperdiet blandit blandit. Nisl eu venenatis dapibus pretium bibendum velit eget feugiat.\n',
  'Ultrices egestas lorem vulputate scelerisque ipsum amet. Consectetur malesuada est lectus massa odio volutpat odio. Turpis vitae donec tincidunt bibendum interdum. Turpis luctus neque nec in cursus aenean. Dui enim ipsum bibendum nunc nisl. Tempor viverra sagittis euismod senectus semper. Eget vestibulum eget molestie imperdiet morbi tellus nulla accumsan. Porta faucibus massa sed amet arcu. Massa leo sit scelerisque sollicitudin tellus nunc et. Lacinia cras massa eget vestibulum. Consectetur posuere semper fames maecenas sit eu non justo. Et leo mauris et urna. Sit id donec commodo vel semper semper. Viverra libero eu mi magna. Risus vivamus id faucibus.',
]
